version: '3.8'

services:
  # Banco de dados do usuárioservice
  postgres-usuario:
    image: postgres:15
    container_name: postgres-usuario
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata-usuario:/var/lib/postgresql/data

  usuarioservice:
    build: ./usuarioservice
    container_name: usuarioservice
    ports:
      - "8081:8083"  # mapeando corretamente a porta 8083 interna
    depends_on:
      - postgres-usuario

  # Banco de dados do salaservice
  postgres-sala:
    image: postgres:15
    container_name: postgres-sala
    environment:
      POSTGRES_DB: salasdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata-sala:/var/lib/postgresql/data

  salaservice:
    build: ./salaservice
    container_name: salaservice
    ports:
      - "8082:8082"  # mapeando corretamente a porta 8082 interna
    depends_on:
      - postgres-sala

  # Banco de dados do reservaservice
  postgres-reserva:
    image: postgres:15
    container_name: postgres-reserva
    environment:
      POSTGRES_DB: reservasdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - pgdata-reserva:/var/lib/postgresql/data

  reservaservice:
    build: ./reservaservice
    container_name: reservaservice
    ports:
    - "8084:8084"
    depends_on:
    - postgres-reserva


volumes:
  pgdata-usuario:
  pgdata-sala:
  pgdata-reserva:
